# Generated by Django 4.2.30 on 2026-04-26 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_skills_started', models.IntegerField(default=0)),
                ('total_skills_completed', models.IntegerField(default=0)),
                ('total_topics_completed', models.IntegerField(default=0)),
                ('total_resources_viewed', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('total_badges_earned', models.IntegerField(default=0)),
                ('total_learning_minutes', models.IntegerField(default=0)),
                ('average_session_minutes', models.FloatField(default=0.0)),
                ('days_active', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('percentile', models.FloatField(default=0.0, help_text='0-100 percentile of users')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('signup', 'User Signup'), ('login', 'User Login'), ('add_xp', 'Added Experience Points'), ('skill_started', 'Skill Started'), ('topic_completed', 'Topic Completed'), ('resource_viewed', 'Resource Viewed'), ('badge_earned', 'Badge Earned'), ('profile_updated', 'Profile Updated'), ('roadmap_generated', 'Roadmap Generated')], max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_ac_user_id_9aae35_idx'), models.Index(fields=['action', '-created_at'], name='activity_ac_action_4b3c59_idx')],
            },
        ),
    ]
