# Generated by Django 4.2.30 on 2026-04-26 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(max_length=10)),
                ('badge_type', models.CharField(choices=[('xp', 'Experience Milestone'), ('streak', 'Learning Streak'), ('skill', 'Skill Expert'), ('social', 'Community Champion'), ('achievement', 'Special Achievement')], max_length=20)),
                ('xp_threshold', models.IntegerField(blank=True, help_text='Unlock at this XP level', null=True)),
                ('streak_threshold', models.IntegerField(blank=True, help_text='Unlock at this streak length', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['badge_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture URL', null=True)),
                ('learning_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('total_xp', models.IntegerField(default=0, help_text='Total experience points earned')),
                ('current_streak', models.IntegerField(default=0, help_text='Days learning consecutively')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest learning streak')),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_xp', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
